#runtime: python27
#api_version: 1
#threadsafe: true
#handlers:
#- url: /
#  static_files: dist/index.html
#  upload: dist/index.html
#- url: /(.*)
#  static_files: dist/\1
#  upload: dist/(.*)

# runtime: nodejs8 # For Node.js 8, use runtime: nodejs8

# instance_class: F2

#env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

#handlers:
# - url: /stylesheets
#   static_dir: stylesheets

#- url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

runtime: nodejs8
